
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSDhkRERUZWZSUWN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1qUXdPVEF5TkRSYUZ3MHpOVEV4TWpJd09UQTNORFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNrc2tWVG5CRUZjUnVCcUVnSHplOFphQ3N1NkFZSTFnMmo1bWUyNkc3d1JYV3dMV0dNa2NnRXl5Uy8KVGlCcG56aUtmY29xa1pGV01TTEZ5YlJFUUl5U1ZwMldCYjI2eUJhbmxKd0h2bXpXMkZXUCtvNy80QnJaV2hFcQpBaWdDbnk1eHZqTGJuWjhXSk12SWw1cmZOUlpndFlYM3lUWW1QeUhsNGt3aEJvSjNmNmdESTE4ZTFBdmgyT05WCjc1bTlQc2QxSnNFMDBaS01qeExaaFhvRkFzOEo1S205NXZ6dmNMbFlwYWNJZ3c2eCtnK1p3ZDlTbzBDZm1uTEUKMjdkTVBsQ21raGlxYmJQbERuS1cwdnhJTDQ4ZExqNzNiUkV4YnRjUjJmcGNqV09TdTNxbUswQllLanBHTk0wcQplTWJnRWc0QXFqaUx1SGpNbzNJYU10anRpVWwvQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTS3FnbjRNNm5JRHM3TEw2ejZzK3lXZFJnU1N6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTBXYy82ZXdUYQpESmJGVjdjY2NtNmIwWHZoNXhhQnJ1QS9sVlVNWnYyQVdCRFJWQUVYd2dodEx0ZWFGWld6QVJTc0hLb0Urb0E1CjBTSFdBME1TMXlUWElMUWtaWnoxeUZPZ2lGZWtOY1hoMWpMZER2VHdtZFdLeTJwNldMOS9KYUtQZTIyaUl1aEwKRWpFeWcwRUYxS2xDYy9jaFVYQURNSS9GK1drbGhYVkUzYngvS1hoZmF5MjZSc1lvN1ErUjZZVEJoWG9DUmRiSwpQU1luYlFVeDMydi8yRWtHZWhra2ZDNHJWaXhjdHBvM1E1bmd4UnFqVWc5bWk0U0dCR05WSkk3alpBa1VvQ25XCkZEZzdzYUtjQk1sa055RHBzMW1HQzdFc2JKVW9WRmhXV3o0RitYOThsNHpJL0FtZkdCaGI1ZlBDaDY0RDY1UXYKUE9DbW5NWjhDaFVxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://40f546f1-de34-47d3-b210-98f1e196c043.us-east-1-gw.linodelke.net:443
  name: lke537066

users:
- name: lke537066-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im9QdHdmUkVaZUw5czJoYXZRcjlWWXBIWmZlTmR0QzFlLUtqdGNYRjUzT3MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tOW4yZ3oiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMDMzZmVlODktYTE0Mi00OGUxLWI2NjctMGI2ZDEwYjczMDc0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.ps_5mALUGW2h5793Ii14U7m3mpXS9Es_dgyScU-gZjhPoe1isigfZtOtdH3kAjg9hF3jIc1kVKLA6O61a3Uocmv1eMwBweXCzw_Ro7XwfrIUWUUHxhsZS-NXXblYUQCGLwLgkbLjx5wN4x-oPE-TiEKVL-q1K_vkIf3GYdjOY5_cLkQJRfuJFugfUiTnvgVPftw3h6_mM6e-DlmmHJXDVyH2IW2Ok2t-sFBPmM8fiwIYTPX-s44Dy6QXc3XxTmmFVWLPcNGwJMgoAD2jgbng5jNRjsXFCIpmUobhIJbqeTyHGbIPFt1oOr9cRBg3ZrguOz8OWJu5OR_20XDY2p0c4w

contexts:
- context:
    cluster: lke537066
    namespace: default
    user: lke537066-admin
  name: lke537066-ctx

current-context: lke537066-ctx
